version: 1.0

workflows:
  flutter-workflow:
    name: Flutter Workflow
    max_build_duration: 60
   
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Run tests
        script: flutter test
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      artifacts:
        - build/app/outputs/flutter-apk/app-release.apk
