version: 2.1

jobs:
  build:
    docker:
        pull: circleci/flutter:3.7.0
      - image: circleci/flutter:3.7.0  # Example tag, verify if this exists
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: flutter pub get
      - run:
          name: Build APK
          command: flutter build apk --split-per-abi --no-tree-shake-icons
      - run:
          name: Build IPA
          command: flutter build ios --release --no-codesign
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: apk
      - store_artifacts:
          path: build/ios/ipa/Runner.ipa
          destination: ipa

workflows:
  version: 2
  flutter-build:
    jobs:
      - build
