# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

workflows:
  flutter-build:
    name: Flutter Build
    max_build_duration: 60
    triggering:
      events:
        - push
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --split-per-abi --no-tree-shake-icons
      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/app-*.apk
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/Runner.ipa
